AppBundle:
  resource:     "@AppBundle/Resources/config/routing.yml"
  prefix:       /{_locale}
  requirements:
    _locale:     es|en
  defaults:
    _locale:     es

_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.xml"
