easy_admin_bundle:
  resource: "@EasyAdminBundle/Controller/"
  type: annotation
  prefix: /admin

AppBundle:
  resource:     "@AppBundle/Resources/config/routing.yml"
  prefix:       /{_locale}
  requirements:
    _locale:     es|en
  defaults:
    _locale:     es
