security:
    firewalls:
      frontend:
        pattern:     ^/*
        anonymous:   ~
        form_login:
          login_path: user_login
          check_path: user_login_check
          default_target_path: list
        logout:
          path: user_logout
          target: user_login
        remember_me:
          key:       mycats1213
          lifetime:  5000

    access_control:
     - { path: ^/front/(es|en)/(login|register|contact|privacy|_wdt), roles: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/front/(es|en)/    , roles: ROLE_USER }
     - { path:  ^/(es|en)/admin, roles: ROLE_ADMIN }

    providers:
      users:
        entity: { class: AppBundle\Entity\User, property: email }

    encoders:
      AppBundle\Entity\User: { algorithm: sha512, iterations: 10 }
