security:
    firewalls:
      admin:
        pattern: ^/admin
        http_basic: 
          realm: "mycats cpanel"
          provider: in_memory
        logout:
          path: /logout
          target: user_login

      frontend:
        pattern:     ^/*
        anonymous:   ~
        form_login:
          login_path: user_login
          check_path: user_login_check
          default_target_path: list
        logout:
          path: user_logout
          target: user_login
        remember_me:
          key:       mycats1213
          lifetime:  5000

    access_control:
     - { path: ^/(es|en)/(login|register|contact|privacy|_wdt), roles: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/(es|en)/*    , roles: ROLE_USER }
     - { path:  ^/admin, roles: ROLE_ADMIN }

    providers:
      users:
        entity: { class: AppBundle\Entity\User, property: email }
      in_memory:
        memory:
          users:
            administrator:
              password: theboss
              roles: ROLE_ADMIN

    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      AppBundle\Entity\User: { algorithm: sha512, iterations: 10 }
