security:
    firewalls:
      frontend:
        pattern:     ^/*
        anonymous:   ~
        form_login:
          login_path: user_login
          check_path: user_login_check
          default_target_path: /list
        logout:
          path: /logout
          target: /login
        remember_me:
          key:       mycats1213
          lifetime:  5000

    access_control:
     - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
     - { path: ^/*    , roles: ROLE_USER }

    providers:
      users:
        entity: { class: AppBundle\Entity\User, property: email }

    encoders:
      AppBundle\Entity\User: { algorithm: sha512, iterations: 10 }
