# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  userManager:
    class:      AppBundle\Security\UserManager
    arguments:  ["@security.encoder_factory"]

  email.new_cat:
    class:  AppBundle\EventListener\EmailListener
    arguments:
      - @mailer
    tags:
      - { name: kernel.event_listener, event: new.cat_created, method: onNewCatCreated }

