contact:
  path:     /contact
  defaults: { _controller: AppBundle:Account:contact }

user_login:
  path:     /
  defaults: { _controller:AppBundle:Account:login }

user_login_check:
  path:     /login_check

user_logout:
  path:     /logout

register:
  path:     /register
  defaults: { _controller:AppBundle:Account:register }
