contact:
  path:     /contact
  defaults: { _controller: AppBundle:Account:contact }

user_login:
  path:     /login
  defaults: { _controller:AppBundle:Account:login }

user_login_check:
  path:     /login_check

user_logout:
  path:     /logout

register:
  path:     /register
  defaults: { _controller:AppBundle:Account:register }

list:
  path:     /list
  defaults: { _controller:AppBundle:Show:list }

list_breed:
  path:     /list/{breed}
  defaults: { _controller:AppBundle:Show:listBreed }

new:
  path:     /new
  defaults: { _controller:AppBundle:User:newCat }

change_breed:
  pattern:      /list/{breed}
  defaults:     { _controller: AppBundle:Show:changeBreed }
  requirements: 
      breed:    .+

user_profile:
  path:     /profile
  defaults: { _controller: AppBundle:Account:editProfile }
