easy_admin_bundle:
  resource: "@EasyAdminBundle/Controller/"
  type: annotation
  prefix: /{_locale}/admin

cpanel:
  path:     /{_locale}/admin

AppBundle:
  resource:     "@AppBundle/Resources/config/routing.yml"
  prefix:       /front/{_locale}
  requirements:
    _locale:     es|en
  defaults:
    _locale:     es

_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.xml"
